# ChirpStack configuration for Raspberry Pi 5

[general]
# Log level
log_level = "info"

# PostgreSQL settings
[postgresql]
dsn = "postgres://chirpstack:chirpstack_postgres_pass@postgres/chirpstack?sslmode=disable"
max_open_connections = 10

# Redis settings
[redis]
servers = ["redis://redis:6379"]

# Network settings
[network]
net_id = "000000"
enabled_regions = ["EU868", "US915", "AS923", "AU915", "CN779", "EU433", "IN865", "KR920", "RU864"]

# API settings
[api]
bind = "0.0.0.0:8080"
secret = "SN9PgGFP/MQSS5Wz7o4SQhNwT0zisvbpk2ZKEny4WCo="

# Integration settings
[integration]
enabled = ["mqtt"]

[integration.mqtt]
server = "tcp://mosquitto:1883/"
json = true

# Gateway backend settings
[gateway]
# Allow unknown gateways
allow_unknown_gateways = true

# Region specific settings
[[regions]]
name = "eu868"
enabled = true

  # Gateway backend configuration for EU868
  [regions.gateway.backend]
  type = "mqtt"
  
  [regions.gateway.backend.mqtt]
  server = "tcp://mosquitto:1883/"
  username = ""
  password = ""
  qos = 0
  clean_session = false
  client_id = ""
  ca_cert = ""
  tls_cert = ""
  tls_key = ""
  
  # Topic templates
  event_topic = "gateway/+/event/+"
  state_topic = "gateway/+/state/+"
  command_topic = "gateway/+/command/+"

[[regions]]
name = "us915"
enabled = true

[[regions]]
name = "as923"
enabled = true

# Device settings
[device_session]
# Deduplication delay (in seconds)
deduplication_delay = "200ms"

# Device queue
[device_session.device_queue]
max_size = 100 