# ChirpStack Gateway Bridge configuration

[general]
log_level = "INFO"

# Gateway backend configuration
[backend]
type = "semtech_udp"

[backend.semtech_udp]
bind = "0.0.0.0:1700"

# Integration configuration
[integration]
type = "mqtt"

[integration.mqtt]
event_topic_template = "eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template = "eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template = "eu868/gateway/{{ .GatewayID }}/command/{{ .CommandType }}"

# MQTT server configuration
server = "tcp://mosquitto:1883"
username = ""
password = ""
clean_session = true

# Gateway ID filters (leave empty to accept all gateways)
[filters]
gateway_ids = [] 